package com.anmi.c4.model.element

enum class ITag {
    E_SYSTEM_TAG,
    E_CONTAINER_TAG,
    E_COMPONENT_TAG,
    OTHER_SYSTEMS_TAG,
    DBS_SYSTEMS_TAG,
    RTRM_SYSTEMS_TAG,

    ERD_COMPONENT,
    STATE_COMPONENT,
    SPRING_REST_CONTROLLER,
    SPRING_SERVICE,
    SPRING_REPOSITORY
}