package com.anmi.c4.model.element

enum class ATag(override val label: String) : ITag {
    WEB_BROWSER("WEB_BROWSER"),
    MOBILE_PHONE("MOBILE_PHONE"),
    DATABASE("DATABASE"),
    MESSAGE_BROKER("MESSAGE_BROKER"),
    A_SYSTEM_TAG("A_SYSTEM_TAG"),
    A_CONTAINER_TAG("A_CONTAINER_TAG"),
    A_COMPONENT_TAG("A_COMPONENT_TAG"),
    OTHER_SYSTEMS_TAG("OTHER_SYSTEMS_TAG"),

    ERD_COMPONENT("ERD_COMPONENT"),
    STATE_COMPONENT("STATE_COMPONENT"),
    SPRING_REST_CONTROLLER("SPRING_REST_CONTROLLER"),
    SPRING_SERVICE("SPRING_SERVICE"),
    SPRING_REPOSITORY("SPRING_REPOSITORY")
}

interface ITag {
    val label: String
}